### PR TITLE
fix: UX messaging around the preview status.

### LINKED ISSUE #158: UX affordance needed when preview fails due to login
Previews may fail because they're behind an auth requirement, and the user may need to login interactively. Currently, we just get this error message (screenshot below).

We need to have a way to either trigger opening the preview page in a new window, or show the root of the preview server in the iframe so the user can login interactively.

image

Currently, this can be worked around by manually opening the preview domain in a new tab to log in, but that's not a reliable way to do this permanently.

### PR DESCRIPTION
**Pull request by Zoramite**
Adds the ability to open the preview server's base url in a window and reloads the preview config either manually or after the 'login' window is closed to test if the request is able to proceed.

image

fixes #158

### CODE REVIEW

File: src/ts/editor/ui/parts/preview/toolbar.ts [hunk 1]
```diff
@@ -58,6 +60,9 @@ export class PreviewToolbarPart extends BasePart implements UiPartComponent {
             break;
           }
         }
+      } else if (devices.length >= 1) {
+        // Default to the first device in the list if none selected.
+        this.device = devices[0];
```
Comment (jeremydw) [inline src/ts/editor/ui/parts/preview/toolbar.ts:65]: Suggestion: Let's default to the last device since it's most likely to be the "desktop" view. The desktop view should be the default for most cases.

**Review by jeremydw — APPROVED** [review]

File: src/ts/editor/ui/parts/preview/toolbar.ts (hunk 1 above)
Comment (Zoramite) [reply src/ts/editor/ui/parts/preview/toolbar.ts:65]: No 'mobile first' design?

Comment (jeremydw) [reply src/ts/editor/ui/parts/preview/toolbar.ts:65]: Realistically in Blinkk we get desktop designs first and we generally build out the desktop designs simultaneously with or before the mobile designs. I can't think of a project where I've received mobile designs before desktop designs, despite the best practice of designing for mobile first.

Comment (Zoramite) [reply src/ts/editor/ui/parts/preview/toolbar.ts:65]: Hmm.. I think instead I'll add a `default` setting to the device config so people can manually specify which device is the default. That way if they have an large desktop it does not become the default since it is last.

Comment (jeremydw) [reply src/ts/editor/ui/parts/preview/toolbar.ts:65]: That sounds fine. I think most of our projects won't configure these settings, and will just rely on the defaults. I'd like the default preview to be the 1400x900 preview (currently "Desktop") for when nothing's selected -- that makes the most sense for our projects and how work is conducted.
